#!/usr/bin/env node
// generate_edition.mjs — dev-time orchestrator for curated parallel editions.
//
// Pipeline (mirrors improve.mjs's posture: dev-time, no SDK, staging-not-live):
//   author parallel MAP  ->  build (staged)  ->  deterministic gate  ->  Chris QC  ->  promote
//
// SAFETY: `generate` writes NOTHING to live data. It stages the tagged Ed1 + the new Ed2
// to editions-staged/ (OUTSIDE _app, so never deployed). `promote` copies the gate-passed
// staged pair to live and prints the editions.json fragment to paste (it never edits the
// hand-maintained manifest itself). An edition is invisible to students until it is BOTH
// in editions.json AND deployed.
//
// Commands:
//   node generate_edition.mjs status
//       Rewrite _app/_games-lab/forge-editions.json (powers the Forge "Editions" UI).
//   node generate_edition.mjs <type> <course> [--slug practice-b] [--map <file>]
//       Generate one staged edition. MAP source: --map file, else ANTHROPIC_API_KEY
//       (autonomous authoring), else print the authoring spec and exit 2 (author under
//       Claude/Max, save the MAP, re-run with --map).
//   node generate_edition.mjs promote <type> <course> [--slug practice-b]
//       Re-gate the staged pair, copy it to live, print the editions.json fragment.
//
// Exit codes: 0 success · 1 failure (gate/validation) · 2 spec printed, nothing generated.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const GF = path.dirname(fileURLToPath(import.meta.url));          // _tools/game-forge
const REPO = path.resolve(GF, '..', '..');
const DATA = path.join(REPO, '_app', '_games-lab', 'data');
const STAGED = path.join(GF, 'editions-staged');                  // outside _app: never deployed
const FORGE_EDITIONS = path.join(REPO, '_app', '_games-lab', 'forge-editions.json');
const EDITIONS_JSON = process.env.EDITIONS_JSON_OVERRIDE || path.join(DATA, 'editions.json'); // override = testability
const API_URL = 'https://api.anthropic.com/v1/messages';
const TYPES = ['jeopardy', 'kahoot', 'wheel', 'fifth'];

// ---- small helpers ------------------------------------------------------------
const readJson = p => JSON.parse(fs.readFileSync(p, 'utf8'));

// Run python3 capturing both streams; throw a useful error on non-zero exit.
function py(script, args) {
  try {
    return execFileSync('python3', [path.join(GF, script), ...args],
      { cwd: REPO, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    const out = (e.stdout || '') + (e.stderr || '');
    throw new Error(`${script} failed (exit ${e.status}):\n${out.trim()}`);
  }
}

// The ordered item list / count for a game doc, per type.
function itemCount(type, doc) {
  if (type === 'jeopardy') return (doc.categories || []).reduce((n, c) => n + (c.clues || []).length, 0);
  if (type === 'wheel') return (doc.puzzles || doc.rounds || []).length;
  return (doc.questions || doc.ladder || []).length; // kahoot, fifth
}

// True if a data filename is a canonical game (no edition slug). `pis.json` yes; `pis.practice-b.json` no.
const isCanonical = f => f.endsWith('.json') && !f.slice(0, -5).includes('.');

// Every canonical game on disk: [{type, course, title, items}]
function listGames() {
  const games = [];
  for (const type of TYPES) {
    const dir = path.join(DATA, type);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir).filter(isCanonical).sort()) {
      const course = f.slice(0, -5);
      const doc = readJson(path.join(dir, f));
      games.push({ type, course, title: doc.title || course, items: itemCount(type, doc) });
    }
  }
  return games;
}

// ---- status: regenerate forge-editions.json -----------------------------------
function buildStatus() {
  // editions.json is the source of truth for what is LIVE/surfaced; reflect only that
  // (staged-but-unpromoted editions are intentionally NOT exposed here).
  const manifest = fs.existsSync(EDITIONS_JSON) ? readJson(EDITIONS_JSON) : {};
  const games = listGames().map(g => {
    const editions = (manifest[g.type] && manifest[g.type][g.course]) || null;
    const parallelCount = editions ? editions.filter(e => !e.canonical).length : 0;
    return {
      type: g.type, course: g.course, title: g.title, canonicalItems: g.items,
      editions: editions || [], parallelCount, hasParallel: parallelCount > 0,
    };
  });
  const out = {
    _comment: 'Generated by generate_edition.mjs status. Per-game edition inventory for the Forge UI. Reflects LIVE editions.json only (staged editions are not listed).',
    games,
  };
  fs.writeFileSync(FORGE_EDITIONS, JSON.stringify(out, null, 2) + '\n');
  const withParallel = games.filter(g => g.hasParallel).length;
  console.log(`status -> ${path.relative(REPO, FORGE_EDITIONS)}  (${games.length} games, ${withParallel} with a parallel edition)`);
}

// ---- authoring spec (the no-key / Claude-under-Max path) -----------------------
function authoringSpec(type, course, ed1, slug) {
  const lines = [];
  lines.push(`# Authoring spec — ${type}/${course} parallel edition "${slug}"`);
  lines.push('');
  lines.push('No --map and no ANTHROPIC_API_KEY, so nothing was generated. Author the parallel');
  lines.push('MAP (via an edu-content-designer subagent or directly), save it, and re-run with --map:');
  lines.push('');
  lines.push(`  node generate_edition.mjs ${type} ${course} --slug ${slug} --map /tmp/edmap_${type}_${course}.json`);
  lines.push('');
  lines.push('RULES: a parallel edition keeps the same structure (same categories+values for jeopardy;');
  lines.push('same item count + per-position gradeTag/value/category for the others) and, at each');
  lines.push('position, tests the SAME learning objective as Ed1 with a FRESH scenario at comparable');
  lines.push('difficulty. Tag each position with a shared `objective` (area:slug). Factual accuracy is');
  lines.push('paramount — a Chris QC gate blocks the edition for any wrong fact.');
  lines.push('');
  if (type === 'jeopardy') {
    lines.push('MAP = JSON array, one object per clue:');
    lines.push('  {"category","value","objective","clue","response","explain"}');
    lines.push('Category names + values must EXACTLY match Ed1. If Ed1 has a top-level categoryLegend /');
    lines.push('jeopardyFormatExample, add one {"_meta":true,"categoryLegend":"...","jeopardyFormatExample":{...}}.');
    lines.push('');
    lines.push('Ed1 positions to cover (category, value):');
    for (const c of ed1.categories) for (const cl of c.clues) lines.push(`  - ${c.name} / ${cl.value}`);
  } else if (type === 'wheel') {
    lines.push('MAP = JSON array aligned 1:1 by index with Ed1 puzzles, each:');
    lines.push('  {"objective","phrase","category","hint","explain"}');
    lines.push('`phrase` must be UPPERCASE letters + spaces ONLY (^[A-Z ]+$); same `category` as Ed1.');
    lines.push('');
    lines.push('Ed1 puzzles:');
    (ed1.puzzles || []).forEach((p, i) => lines.push(`  [${i}] ${p.category} :: ${p.phrase}`));
  } else { // kahoot, fifth
    lines.push('MAP = JSON array aligned 1:1 by index with Ed1 questions, each:');
    lines.push('  {"objective","q","options":[4],"answer":<idx>,"note","explain":{"correct","wrong":[...]}}');
    lines.push('`wrong` is index-aligned to options with "" at the answer index.');
    if (type === 'fifth') lines.push('Do NOT emit value/gradeTag/milestone — they are preserved from Ed1.');
    lines.push('');
    lines.push('Ed1 questions:');
    (ed1.questions || []).forEach((q, i) => lines.push(`  [${i}] ${type === 'fifth' ? '(' + (q.gradeTag || '') + ') ' : ''}${q.q}`));
  }
  return lines.join('\n');
}

// ---- autonomous authoring via Anthropic (only when ANTHROPIC_API_KEY is set) ---
async function authorWithClaude(type, course, ed1, slug, key) {
  const spec = authoringSpec(type, course, ed1, slug);
  const system = 'You are an expert IT/CS exam author. Output ONLY a JSON array (the MAP). No prose, no code fences.';
  const user = spec + '\n\nReturn ONLY the JSON array described above.';
  const res = await fetch(API_URL, {
    method: 'POST',
    headers: { 'x-api-key': key, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' },
    body: JSON.stringify({ model: 'claude-sonnet-4-6', max_tokens: 16000, temperature: 0.4, system, messages: [{ role: 'user', content: user }] }),
  });
  if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const data = await res.json();
  const text = data.content.map(b => b.text || '').join('');
  const m = text.match(/\[[\s\S]*\]/);
  if (!m) throw new Error('no JSON array found in model response');
  return JSON.parse(m[0]);
}

// Light shape check BEFORE shelling out, so a malformed MAP fails clearly here (not as a
// cryptic Python error). Deep validation still happens in the build script + gate.
function validateMapShape(type, map, ed1) {
  if (!Array.isArray(map)) throw new Error('MAP must be a JSON array');
  const clues = map.filter(e => !e._meta);
  if (type === 'jeopardy') {
    const need = itemCount('jeopardy', ed1);
    if (clues.length !== need) throw new Error(`MAP has ${clues.length} clues, Ed1 has ${need}`);
    for (const e of clues) for (const k of ['category', 'value', 'objective', 'clue', 'response', 'explain'])
      if (e[k] === undefined || e[k] === '') throw new Error(`MAP entry missing '${k}': ${JSON.stringify(e).slice(0, 80)}`);
  } else {
    const need = itemCount(type, ed1);
    if (map.length !== need) throw new Error(`MAP has ${map.length} items, Ed1 has ${need}`);
    const req = type === 'wheel' ? ['objective', 'phrase', 'category', 'hint', 'explain']
                                 : ['objective', 'q', 'options', 'answer', 'explain'];
    map.forEach((e, i) => { for (const k of req) if (e[k] === undefined) throw new Error(`MAP[${i}] missing '${k}'`); });
  }
}

// ---- generate one staged edition ----------------------------------------------
async function generate(type, course, slug, mapPath) {
  const ed1Path = path.join(DATA, type, `${course}.json`);
  if (!fs.existsSync(ed1Path)) throw new Error(`no canonical game at ${path.relative(REPO, ed1Path)}`);
  const ed1 = readJson(ed1Path);

  // 1) obtain the MAP
  let map;
  if (mapPath) {
    map = readJson(mapPath);
  } else if (process.env.ANTHROPIC_API_KEY) {
    console.log(`authoring MAP via Anthropic (claude-sonnet-4-6)…`);
    map = await authorWithClaude(type, course, ed1, slug, process.env.ANTHROPIC_API_KEY);
  } else {
    console.log(authoringSpec(type, course, ed1, slug));
    process.exit(2); // spec printed, nothing generated
  }
  validateMapShape(type, map, ed1);

  // 2) build into the staging dir (live data untouched)
  const stageDir = path.join(STAGED, type);
  fs.mkdirSync(stageDir, { recursive: true });
  const tmpMap = path.join(STAGED, `_map_${type}_${course}_${slug}.json`);
  fs.writeFileSync(tmpMap, JSON.stringify(map, null, 2));
  if (type === 'jeopardy') {
    py('build_jeopardy_edition.py', [course, slug, 'Jeopardy Review — Practice Set B', tmpMap, '--out-dir', stageDir]);
  } else {
    py('build_seq_edition.py', [type, course, slug, 'Practice Set B', tmpMap, '--out-dir', stageDir]);
  }

  // 3) deterministic gate on the staged pair (additive vs current live)
  const stagedEd1 = path.join(stageDir, `${course}.json`);
  const stagedEd2 = path.join(stageDir, `${course}.${slug}.json`);
  const gate = py('edition_gate.py', [type, course, slug, '--ed1', stagedEd1, '--ed2', stagedEd2]);
  process.stdout.write(gate);

  console.log(`\nSTAGED (not live): ${path.relative(REPO, stagedEd2)}`);
  console.log('Next: Chris-QC the staged Ed2 (factual + parallel-validity + objective-honesty), then:');
  console.log(`  node generate_edition.mjs promote ${type} ${course} --slug ${slug}`);
}

// Human label for a slug: "practice-b" -> "Practice Set B".
function editionLabel(slug) {
  const m = /^practice-([a-z0-9]+)$/.exec(slug);
  if (m) return `Practice Set ${m[1].toUpperCase()}`;
  return slug.replace(/(^|-)([a-z0-9])/g, (_, s, c) => (s ? ' ' : '') + c.toUpperCase());
}

// Idempotently register (type,course,slug) in editions.json, preserving the file's
// _comment + key order. Returns true if the file changed. Manifest is written BEFORE
// the Ed2 file is copied to live, so the unsafe state (live Ed2 with no manifest entry)
// never exists — a deploy at any point yields at worst a dead chip (graceful 404), not
// un-QC'd content reachable by URL.
export function ensureManifestEntry(type, course, slug) {
  const manifest = fs.existsSync(EDITIONS_JSON) ? readJson(EDITIONS_JSON) : {};
  if (!manifest[type]) manifest[type] = {};
  if (!manifest[type][course]) {
    manifest[type][course] = [{ id: 'core', label: 'Core Set', canonical: true, note: `The original ${course} questions.` }];
  }
  const list = manifest[type][course];
  if (list.some(e => e.id === slug)) return false; // already registered — idempotent
  list.push({ id: slug, label: editionLabel(slug), note: 'Parallel form — same objectives, fresh scenarios.' });
  fs.writeFileSync(EDITIONS_JSON, JSON.stringify(manifest, null, 2) + '\n'); // preserves _comment (first key) + order
  return true;
}

// ---- promote a staged edition to live ------------------------------------------
function promote(type, course, slug) {
  const stageDir = path.join(STAGED, type);
  const stagedEd1 = path.join(stageDir, `${course}.json`);
  const stagedEd2 = path.join(stageDir, `${course}.${slug}.json`);
  if (!fs.existsSync(stagedEd2)) throw new Error(`no staged edition at ${path.relative(REPO, stagedEd2)} — run generate first`);

  // re-gate before promoting (defense in depth)
  process.stdout.write(py('edition_gate.py', [type, course, slug, '--ed1', stagedEd1, '--ed2', stagedEd2]));

  // 1) register in editions.json FIRST (safe ordering — see ensureManifestEntry)
  const added = ensureManifestEntry(type, course, slug);
  // 2) then copy the gate-passed staged pair to live
  fs.copyFileSync(stagedEd1, path.join(DATA, type, `${course}.json`));
  fs.copyFileSync(stagedEd2, path.join(DATA, type, `${course}.${slug}.json`));
  // 3) refresh the Forge dashboard manifest
  buildStatus();

  console.log(`\npromoted ${type}/${course} edition "${slug}" -> live`);
  console.log(added ? `  + registered in editions.json (label "${editionLabel(slug)}")`
                    : `  (editions.json already had "${slug}")`);
  console.log('  Review `git diff` of data/editions.json + the new files, then commit + deploy.');
}

// ---- main ---------------------------------------------------------------------
async function main() {
  const argv = process.argv.slice(2);
  const flag = (name) => { const i = argv.indexOf(name); if (i < 0) return null; const v = argv[i + 1]; argv.splice(i, 2); return v; };
  const slug = flag('--slug') || 'practice-b';
  const mapPath = flag('--map');
  const [cmd, type, course] = argv;

  const usage = 'usage:\n  generate_edition.mjs status\n  generate_edition.mjs <type> <course> [--slug practice-b] [--map <file>]\n  generate_edition.mjs promote <type> <course> [--slug practice-b]';
  if (cmd === 'status') return buildStatus();
  if (cmd === 'promote') {
    if (!TYPES.includes(type) || !course) { console.error(usage); process.exit(1); }
    return promote(type, course, slug);
  }
  // default: generate. Here `cmd` is the game type and `type` is the course id.
  if (!TYPES.includes(cmd) || !type) { console.error(usage); process.exit(1); }
  return generate(cmd, type, slug, mapPath);
}

// Run main() only when invoked directly (lets tests import the helpers above).
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(e => { console.error('ERROR: ' + e.message); process.exit(1); });
}
