#!/usr/bin/env bash
# push_hub_inventory.sh — regenerate the Confluence "Hexworth Prime — Complete
# Course & Hub Inventory" page (id 4358163) from the current filesystem state
# and push it as a new version.
#
# Designed for invocation from deploy.sh as a post-deploy step. NEVER blocks
# or fails the calling deploy — all errors are caught and logged. Exit code is
# always 0 from this script's perspective; non-fatal failures print a warning.
#
# Usage:
#   _tools/confluence/push_hub_inventory.sh         # regen + push, log result
#   _tools/confluence/push_hub_inventory.sh --dry   # regen only, skip push
#
# Prerequisites:
#   - ~/.config/confluence/credentials.json with {email, token, domain}
#   - node, jq, curl
#
# Failure modes that are handled gracefully (warn, exit 0):
#   - missing credentials file
#   - missing required CLI tools
#   - Confluence API error (auth, network, rate limit, 5xx)
#   - filesystem walk error
#   - script crash

set +e   # explicitly disable exit-on-error — this script is non-blocking by contract

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DRY=false
PAGE_ID=4358163

for arg in "$@"; do
    case "$arg" in
        --dry|--dry-run) DRY=true ;;
        *) ;;  # ignore unknown for forward-compat
    esac
done

warn() { echo "[confluence-inventory] WARN: $1" >&2; }
log()  { echo "[confluence-inventory] $1"; }

# Tool checks
for tool in node jq curl; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        warn "missing $tool — skipping inventory regen"
        exit 0
    fi
done

# Credentials check
CRED_FILE="$HOME/.config/confluence/credentials.json"
if [ ! -f "$CRED_FILE" ]; then
    warn "no credentials at $CRED_FILE — skipping inventory regen (set up Confluence creds to enable)"
    exit 0
fi

EMAIL=$(jq -r '.email // empty' "$CRED_FILE" 2>/dev/null)
TOKEN=$(jq -r '.token // empty' "$CRED_FILE" 2>/dev/null)
DOMAIN=$(jq -r '.domain // "hexworth.atlassian.net"' "$CRED_FILE" 2>/dev/null)
if [ -z "$EMAIL" ] || [ -z "$TOKEN" ]; then
    warn "credentials missing email or token — skipping"
    exit 0
fi

# Builder check
BUILDER="$SCRIPT_DIR/build_hub_inventory.js"
if [ ! -f "$BUILDER" ]; then
    warn "builder script not found at $BUILDER — skipping"
    exit 0
fi

cd "$REPO_ROOT" || { warn "cannot cd to repo root — skipping"; exit 0; }

# Regenerate (writes /tmp/inv_new_storage.html as side effect of build script)
if ! node "$BUILDER" >/dev/null 2>&1; then
    warn "builder script crashed — skipping push (run manually to debug: node $BUILDER)"
    exit 0
fi
if [ ! -f /tmp/inv_new_storage.html ]; then
    warn "builder produced no output — skipping"
    exit 0
fi

if [ "$DRY" = true ]; then
    log "dry-run: built $(wc -c < /tmp/inv_new_storage.html) chars, not pushing"
    exit 0
fi

# Read current page version (need it +1 for the PUT)
META=$(curl -sf --max-time 15 \
    -u "${EMAIL}:${TOKEN}" \
    "https://${DOMAIN}/wiki/rest/api/content/${PAGE_ID}?expand=version" 2>/dev/null)
if [ -z "$META" ]; then
    warn "Confluence page metadata fetch failed (auth/network/page-not-found) — skipping"
    exit 0
fi

CURRENT_VER=$(echo "$META" | jq -r '.version.number // empty' 2>/dev/null)
if [ -z "$CURRENT_VER" ] || ! [[ "$CURRENT_VER" =~ ^[0-9]+$ ]]; then
    warn "could not parse current version from API response — skipping"
    exit 0
fi
NEXT_VER=$((CURRENT_VER + 1))

log "Confluence current version: $CURRENT_VER → pushing $NEXT_VER"

# Build the JSON payload
PAYLOAD_FILE=$(mktemp)
jq -n \
    --arg title "Hexworth Prime — Complete Course & Hub Inventory" \
    --arg body "$(cat /tmp/inv_new_storage.html)" \
    --argjson version "$NEXT_VER" \
    '{
        version: { number: $version, message: "Auto-regenerated by deploy.sh post-deploy hook (filesystem walk on master HEAD)" },
        title: $title,
        type: "page",
        body: { storage: { value: $body, representation: "storage" } }
    }' > "$PAYLOAD_FILE" 2>/dev/null
if [ ! -s "$PAYLOAD_FILE" ]; then
    warn "JSON payload generation failed — skipping"
    rm -f "$PAYLOAD_FILE"
    exit 0
fi

# PUT to Confluence (bounded timeout)
RESP=$(curl -sf -X PUT --max-time 30 \
    -u "${EMAIL}:${TOKEN}" \
    -H "Content-Type: application/json" \
    -d @"$PAYLOAD_FILE" \
    "https://${DOMAIN}/wiki/rest/api/content/${PAGE_ID}" 2>/dev/null)
RC=$?
rm -f "$PAYLOAD_FILE"

if [ $RC -ne 0 ] || [ -z "$RESP" ]; then
    warn "Confluence PUT failed (curl exit $RC) — page NOT updated. Run manually to retry: $0"
    exit 0
fi

NEW_VER=$(echo "$RESP" | jq -r '.version.number // empty' 2>/dev/null)
if [ "$NEW_VER" = "$NEXT_VER" ]; then
    log "Inventory page updated to v${NEW_VER} — https://${DOMAIN}/wiki/spaces/KBA/pages/${PAGE_ID}"
else
    warn "PUT response did not confirm v${NEXT_VER} (got: ${NEW_VER:-empty}) — verify manually"
fi

exit 0
