"""
Project-hub QC sweep. Scans every _app/projects/*.html for the defect classes that have
bitten this catalog. Run before registering/shipping project pages.

Checks:
  - DUPLICATE-DOCUMENT (added 2026-06-13): more than one <head>/<body>/<!DOCTYPE> per file.
    This is the defect that slipped past an earlier sweep + two reviews on the 12 orphan
    pages (two HTML fragments spliced together). Caught by the Chris gate; now checked here.
  - Broken internal .html links (href targets that don't resolve)
  - Emoji (banned platform-wide)
  - AI attribution strings (banned)
  - Stub pages (< 3 KB)
  - Missing <title>
Exit non-zero if any blocking defect (duplicate-doc, broken link, emoji, AI-attr, stub) is found.
"""
import os, re, glob, sys

PROJ = '/home/eq/ai-content/hexworth-prime/_app/projects'
APP  = '/home/eq/ai-content/hexworth-prime/_app'
EMOJI = re.compile('[\U0001F300-\U0001FAFF\U00002600-\U000026FF\U00002700-\U000027BF]')
AI_ATTR = re.compile(r'(generated by (claude|ai|chatgpt|gpt)|co-authored-by|as an ai language model)', re.I)

dup_doc, broken, emoji_hits, ai_hits, stubs, no_title = {}, {}, {}, {}, [], []

for p in sorted(glob.glob(os.path.join(PROJ, '*.html'))):
    name = os.path.basename(p)
    h = open(p, encoding='utf-8').read()
    # Duplicate-document defect: a well-formed single page has exactly one of each.
    counts = {'<head>': h.count('<head>'), '</head>': h.count('</head>'),
              '<body>': h.count('<body>'), '<!DOCTYPE': h.count('<!DOCTYPE')}
    if any(c > 1 for c in counts.values()):
        dup_doc[name] = counts
    if len(h) < 3000:
        stubs.append((name, len(h)))
    if '<title>' not in h:
        no_title.append(name)
    # Emoji: banned platform-wide (icons are webp images, not emoji glyphs).
    em = [c for c in EMOJI.findall(h)]
    if em:
        emoji_hits[name] = len(em)
    # AI-attribution strings are banned in shipped content.
    if AI_ATTR.search(h):
        ai_hits[name] = True
    # Resolve every internal .html link against the hosting root (_app) or the page dir
    # and flag any target that does not exist on disk.
    bad = []
    for m in re.finditer(r'href="([^"]+\.html)(?:#[^"]*)?"', h):
        t = m.group(1)
        if t.startswith('http') or t.startswith('//'):
            continue
        r = os.path.join(APP, t.lstrip('/')) if t.startswith('/') else os.path.normpath(os.path.join(PROJ, t))
        if not os.path.exists(r):
            bad.append(t)
    if bad:
        broken[name] = sorted(set(bad))

# Print one section of the report: a heading with the count, then each offending entry.
def report(title, d):
    print(f"\n=== {title} ({len(d)}) ===")
    for k in (d if isinstance(d, dict) else d):
        print(f"  {k}: {d[k] if isinstance(d, dict) else ''}")

report("DUPLICATE-DOCUMENT defect", dup_doc)
report("BROKEN internal links", broken)
report("EMOJI", emoji_hits)
report("AI ATTRIBUTION", ai_hits)
print(f"\n=== STUBS <3KB ({len(stubs)}) ===")
for n, sz in stubs: print(f"  {n}: {sz}b")
print(f"\n=== MISSING <title> ({len(no_title)}) ===")
for n in no_title: print(f"  {n}")

# Tally blocking defects (everything except the advisory missing-<title>) and exit non-zero
# if any are present, so the sweep can gate a deploy.
blocking = len(dup_doc) + len(broken) + len(emoji_hits) + len(ai_hits) + len(stubs)
print(f"\n{'FAIL' if blocking else 'PASS'}: {blocking} blocking defect(s) across {len(glob.glob(os.path.join(PROJ,'*.html')))} pages.")
sys.exit(1 if blocking else 0)
